---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ordering-service-ingress
spec:
  ingressClassName: alb
  rules:
  - host: "starinc.com"
    http:
      paths:
      - path: /order
        pathType: Prefix
        backend:
          service:
            name: starinc-order-service
            port:
              number: 9376
---
apiVersion: v1
kind: Service
metadata:
  name: starinc-order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 9376
      targetPort: 9376
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: starinc-order-service-deployment
  labels:
    app: starinc-order-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: starinc-order-service
  template:
    metadata:
      labels:
        app: starinc-order-service
    spec:
      containers:
      - name: order-service
        image: order-service:1.0.0
        ports:
        - containerPort: 9376
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        lifecycle:
          preStop:
            exec:
              command:
                - "/bin/bash"
                - "sleep 20"
      affinity:
        podAntiAffinity: # make sure the pod span accross all azs
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - web-server
              topologyKey: topology.kubernetes.io/zone
            weight: 100               
---